on: workflow_dispatch

jobs:
  build-debs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install required packages
        run: |
          pwd
          sudo apt update
          sudo bash -c 'echo "force-unsafe-io" > /etc/dpkg/dpkg.cfg.d/force-unsafe-io'
          sudo apt install -y --no-install-recommends dh-make-golang curl build-essential ca-certificates cowbuilder debian-archive-keyring
          which -a go
          go version

      - name: Create the moo cow
        run: DIST=unstable sudo cowbuilder --create --distribution unstable --mirror https://deb.debian.org/debian

      - name: Run dh-make-golang
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          dh-make-golang github.com/ollama/ollama

      - name: Build the package
        run: |
          cd ollama
          git add debian && git commit -a -m 'Initial packaging'
          gbp buildpackage --git-pbuilder
