on: push

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Do it
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
          DEBFULLNAME: ollama
        run: |
          pwd
          sudo apt update
          sudo apt install -y --no-install-recommends dh-make curl build-essential ca-certificates
          curl -L 'https://github.com/ollama/ollama/releases/download/v0.3.14/ollama-linux-amd64.tgz' -O
          curl -L --silent 'https://raw.githubusercontent.com/ollama/ollama/refs/heads/main/LICENSE' -O
          mkdir -p ollama-0.3.14/tmp
          cd ollama-0.3.14/
          tar zxvf ../ollama-linux-amd64.tgz -C tmp
          ls -lR
          dh_make --single --packagename ollama_0.3.14 --copyright custom --copyrightfile ../../LICENSE --email ollama@ollama.com --native --yes
          dpkg-buildpackage -b -us -uc
