on: push

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Do it
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
          DEBFULLNAME: ollama
        run: |
          pwd
          sudo apt update
          sudo apt install -y --no-install-recommends dh-make curl build-essential ca-certificates
          curl -L 'https://github.com/ollama/ollama/releases/download/v0.3.14/ollama-linux-amd64.tgz' -O
          curl -L --silent 'https://raw.githubusercontent.com/ollama/ollama/refs/heads/main/LICENSE' -O
          mkdir -p ollama-0.3.14/tmp
          cd ollama-0.3.14/
          tar zxvf ../ollama-linux-amd64.tgz -C tmp
          ls -lR
          dh_make --single --packagename ollama_0.3.14 --copyright custom --copyrightfile ../../LICENSE --email ollama@ollama.com --native --yes
          rm -f debian/install
          
          # Iterate over all files in the tmp directory
          for file in tmp/bin/*; do
            # Skip directories (only process files)
            if [ -f "$file" ]; then
              f=$(basename -- "$file")
              echo "tmp/bin/$f usr/bin/" >> debian/install
            fi
          done
          
          for file in tmp/lib/ollama/*; do
            # Skip directories (only process files)
            if [ -f "$file" ]; then
              f=$(basename -- "$file")
              echo "tmp/lib/ollama/$f usr/lib/" >> debian/install
            fi
          done
          dpkg-buildpackage -b -us -uc
      - name: Release
        uses: softprops/action-gh-release@v2
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          files: *.deb
