on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install required packages
        run: |
          pwd
          sudo apt update
          sudo apt install -y --no-install-recommends dh-make curl build-essential ca-certificates

      - name: Download ollama
        run: |
          pwd
          curl -L --no-progress-meter 'https://github.com/ollama/ollama/releases/download/v0.3.14/ollama-linux-amd64.tgz' -O
          curl -L --no-progress-meter 'https://raw.githubusercontent.com/ollama/ollama/refs/heads/main/LICENSE' -O
          ls -lR

      - name: Create skeleton and extract ollama
        run: |
          pwd
          mkdir -p ollama-0.3.14/tmp
          cd ollama-0.3.14/
          tar zxvf ../ollama-linux-amd64.tgz -C tmp
          ls -lR

      - name: Run dh_make to create packaging files
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
          DEBFULLNAME: ollama
        run: |
          pwd
          cd ollama-0.3.14/
          dh_make --single --packagename ollama_0.3.14 --copyright custom --copyrightfile ../../LICENSE --email ollama@ollama.com --native --yes
          bash ../mkinstall.sh

      - name: Build the package
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
          DEBFULLNAME: ollama
        run: |
          pwd
          cd ollama-0.3.14/
          dpkg-buildpackage -b -us -uc
          cd ..
          ls -lR

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.deb"
