on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install required packages
        run: |
          pwd
          echo "force-unsafe-io" > /etc/dpkg/dpkg.cfg.d/force-unsafe-io
          sudo apt update
          sudo apt install -y --no-install-recommends dh-make curl build-essential ca-certificates

      - name: Download latest ollama
        uses: robinraju/release-downloader@v1
        with:
          repository: 'ollama/ollama'
          tag: ${{ github.ref_name }}
          fileName: 'ollama-linux-amd64.tgz'

      - name: Download license
        run: |
          curl -L --no-progress-meter 'https://raw.githubusercontent.com/ollama/ollama/refs/heads/main/LICENSE' -O

      - name: Create skeleton and extract ollama
        run: |
          pwd
          mkdir -p ollama-${{ github.ref_name }}/tmp
          cd ollama-${{ github.ref_name }}/
          tar zxvf ../ollama-linux-amd64.tgz -C tmp
          ls -lR

      - name: Run dh_make to create packaging files
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
          DEBFULLNAME: ollama
        run: |
          pwd
          cd ollama-${{ github.ref_name }}/
          dh_make --single --packagename ollama_${{ github.ref_name }} --copyright custom --copyrightfile ../../LICENSE --email ollama@ollama.com --native --yes
          bash ../mkinstall.sh

      - name: Build the package
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
          DEBFULLNAME: ollama
        run: |
          pwd
          cd ollama-${{ github.ref_name }}/
          dpkg-buildpackage -b -us -uc
          cd ..
          ls -lR

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.deb"
