name: Build new release

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Remove tag semver v
        run: |
          echo "VERSION_NO_V=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Install required packages
        run: |
          pwd
          sudo apt update
          sudo bash -c 'echo "force-unsafe-io" > /etc/dpkg/dpkg.cfg.d/force-unsafe-io'
          sudo apt install -y --no-install-recommends dh-make curl build-essential ca-certificates dh-sysuser

      - name: Download latest ollama
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download ${GITHUB_REF_NAME} --repo https://github.com/ollama/ollama -p ollama-linux-amd64.tgz

      - name: Download ollama source
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download ${GITHUB_REF_NAME} --repo https://github.com/ollama/ollama --archive tar.gz

      - name: Create skeleton and extract ollama
        run: |
          pwd
          mkdir -p ollama-${VERSION_NO_V}/tmp
          cd ollama-${VERSION_NO_V}/
          tar zxvf ../ollama-linux-amd64.tgz -C tmp

      - name: Extract ollama docs and license
        run: |
          cd ollama-${VERSION_NO_V}/
          tar --strip-components 1 -zxvf ../ollama-${VERSION_NO_V}.tar.gz ollama-${VERSION_NO_V}/docs ollama-${VERSION_NO_V}/LICENSE

      - name: Run dh_make to create packaging files
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
          DEBFULLNAME: ollama
        run: |
          pwd
          ls -l
          cd ollama-${VERSION_NO_V}/
          dh_make --single --packagename ollama_${VERSION_NO_V} --copyright custom --copyrightfile ../LICENSE --email ollama@ollama.com --native --yes
          # bash ../mkinstall.sh
          cp -v ../packaging_files/* debian/

      - name: Build the package
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
          DEBFULLNAME: ollama
        run: |
          pwd
          cd ollama-${VERSION_NO_V}/
          dpkg-buildpackage -b -us -uc
          cd ..
          ls -lR

      - name: Grab .deb file contents
        run: |
          echo "This is release ${GITHUB_REF_NAME}." > CONTENTS.md
          echo "" >> CONTENTS.md
          echo "deb file contents:" >> CONTENTS.md
          echo "" >> CONTENTS.md
          echo '```' >> CONTENTS.md
          dpkg -c *.deb >> CONTENTS.md
          echo '```' >> CONTENTS.md

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.deb"
          body_path: CONTENTS.md
