name: Poll for new tags

on:
  schedule:
    - cron: '0 * * * *'  # This runs the action every hour (adjust as needed)
  workflow_dispatch:

jobs:
  check-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check for new tags
        id: check_tags
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the latest tag from ollama/ollama
          their_latest_tag=$(gh release list --repo https://github.com/ollama/ollama --json tagName --jq '.[] | .tagName' --limit 1)
          echo "Their latest tag: $their_latest_tag"
          echo "::set-output name=their_latest_tag::${their_latest_tag}"
          
          # Get the latest tag from this repository
          our_latest_tag=$(gh release list --repo ${{ github.repositoryUrl }} --json tagName --jq '.[] | .tagName' --limit 1)
          echo "Our latest tag: $our_latest_tag"
          echo "::set-output name=our_latest_tag::${our_latest_tag}"

      - name: Create new tag if new tag found
        if: steps.check_tags.outputs.their_latest_tag != steps.check_tags.outputs.our_latest_tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          new_tag=${{ steps.check_tags.outputs.their_latest_tag }}
          echo "Creating new tag: $new_tag"
          # Create a new tag in this repository
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag $new_tag
          git push origin $new_tag


      - name: Trigger main.yml workflow
        if: steps.check_tags.outputs.their_latest_tag != steps.check_tags.outputs.our_latest_tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches \
            -d '{"ref":"main"}'
            
