name: Poll for New Tags

on:
  schedule:
    - cron: '0 * * * *'  # This runs the action every hour (adjust as needed)

jobs:
  check-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Check for new tags
        id: check_tags
        run: |
          # Get the latest tag
          their_latest_tag=$(gh release list --repo https://github.com/ollama/ollama --json tagName --jq '.[] | .tagName' --limit 1)
          echo "Their latest tag: $their_latest_tag"
          #echo "::set-output name=latest_tag::$latest_tag"
          our_latest_tag=$(gh release list --repo ${github.repositoryUrl} --json tagName --jq '.[] | .tagName' --limit 1)
          echo "Our latest tag: $our_latest_tag"


      - name: Trigger action if new tag found
        if: steps.check_tags.outputs.latest_tag != 'YOUR_LAST_KNOWN_TAG'
        run: |
          echo "New tag detected: ${{ steps.check_tags.outputs.latest_tag }}"
          # Add your action logic here
