name: Test deb file install

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download latest release
        run: |
          gh release download --pattern '*.deb'

      - name: Install it
        run: |
          sudo apt update
          apt install ./*.deb
          
